07-John-Childs-Eddy/newfile.html
=> This is a test push

08-Nick-Waddington/wk01/1-mon/commands.txt
- How difficult did you find this (out of 10)? (0 being no problems at all, 10 being impossible) 6
- Was there anything that you struggled with? - I feel I was quite inefficient with making and moving multiple directories.
- Is there any particular code you want me to look into? N/A
- Is there anything that you'd like some further information on? - Is it possible to move different files into different directories in the same line of code?
- Roughly how long did it take? A bit over an hour
=> Command list for starwars activity

13-Wayne-Kenny/wk01/1-mon/commands.txt
=> adding commands to homework

.gitignore, 06-Jeffrey-Fazal/Demo - First file, 06-Jeffrey-Fazal/wk01/1-mon/commands.txt.save, 06-Jeffrey-Fazal/wk01/1-mon/galaxy_far_far_away/a-new-terminal.md
2/10
Attention to detail, the fictional scenario was annoying more that confusing. 
It was a bit tedious updating the comands.txt file so I gave up. 
Is there an easy way of saving the useful commands you've run? 
1hr or so
=> Added Episode X project | Disney bought out Star Wars & nothing is cannon. 

11-Tanakorn-Treechorvitaya/wk01/1-mon/command.txt
- How difficult did you find this (out of 10)? (0 being no problems at all, 10 being impossible) 
- = 3
- Was there anything that you struggled with? 
- = move copy and remove as using incorrect directory to reference and have to redo every staffs over and over
- Is there any particular code you want me to look into? 
- = move copy and remove
- Is there anything that you'd like some further information on? 
- = is it possible to move both source and destination in any level by using reference? 
- = 1.5 hours
=> Submit Homework for Tanakorn

12-Vincent-Choi/wk01/1-mon/commands.txt
- It was a little tough made some silly errors even at the end when uploading
- Was there anything that you struggled with? Figuring out the moving paths 
- Is there any particular code you want me to look into? Not really, maybe the moving paths
- Is there anything that you'd like some further information on? Is there a way to move multiple folders to another folder without renaming it?
- Roughly how long did it take? It took around 2 hours
=> wk01_1-mon Elevader Homework

09-Nicole-Low/wk01/1-mon/commands.txt
=> wk01_1-mon homework submission

15-James-Pan/wk01/1-mon/commands.txt
- 3
- move multiple files at once
- NA
- the way to control multiple files - move, copy etc.
- a hour and half
=> week1 day1 homework

03-Debora-Jardim/wk01/1-mon/commands.txt
=> homework files

02-Brianna-Danford/wk01/1-mon/commands.txt
=> Episode X: A new terminal -edited

04-Haoran-Guo/wk01/1-mon/command.txt
- How difficult did you find this (out of 10)? (0 being no problems at all, 10 being impossible) 2
- Was there anything that you struggled with? move multiple folders 
- Is there any particular code you want me to look into? mv --from folderA, folderB --to destinationPath
- Roughly how long did it take? 40min
=> First Day Homework

09-Nicole-Low/wk01/2-tue/index.html, 09-Nicole-Low/wk01/2-tue/script.js
=> wk1-d2 homework submission

02-Brianna-Danford/wk01/2-tue/index.html, 02-Brianna-Danford/wk01/2-tue/script.js
2
Implementing a flowchart into code in JS.
1hr
=> JS Primitives and Conditionals

06-Jeffrey-Fazal/wk01/2-tue/index.html, 06-Jeffrey-Fazal/wk01/2-tue/js-primitives-conditionals.md, 06-Jeffrey-Fazal/wk01/2-tue/script.js
4/10
Time management. Tried to do some DOM stuff and use arrays. Should probably do simple stuff first and then play around
Not sure if there was a simpler way to tackle the last flow chart solution
n.a
-3 hours with trying to experiment.
=> w01d02 Solutions uploaded

08-Nick-Waddington/wk01/2-tue/index.html, 08-Nick-Waddington/wk01/2-tue/script.js
- How difficult did you find this (out of 10)? (0 being no problems at all, 10 being impossible) 6
- Was there anything that you struggled with? - getting the program to differentiate string responses from the prompt
- Roughly how long did it take? - about an hour
=> answers for javascript problems

10-Penelope-Chen/wk01/2-tue/index.html, 10-Penelope-Chen/wk01/2-tue/script.js
=> JS Conditionals & Primitives

07-John-Childs-Eddy/wk01/2-tue/index.html, 07-John-Childs-Eddy/wk01/2-tue/script.js
=> completed homework

14-Wing-Fung-Lau/wk01/2-tue/index.html, 14-Wing-Fung-Lau/wk01/2-tue/script.js
=> Human World Day is on 10 December!

11-Tanakorn-Treechorvitaya/wk02/2-tue/index.html, 11-Tanakorn-Treechorvitaya/wk02/2-tue/script.js
- How difficult did you find this (out of 10)? (0 being no problems at all, 10 being impossible) 1
- Was there anything that you struggled with? no
- Is there any particular code you want me to look into? no
- Is there anything that you'd like some further information on? no
- Roughly how long did it take? 30 mins
=> submit hw for w1d2 TanakornT

12-Vincent-Choi/wk01/1-mon/commands.txt, 12-Vincent-Choi/wk01/2-tue/index.html, 12-Vincent-Choi/wk01/2-tue/script.js
- How difficult did you find this (out of 10)? This time around was fairly straight forward (0 being no problems at all, 10 being impossible)
- Was there anything that you struggled with? Maybe with the last task not sure if i did it correctly
- Is there any particular code you want me to look into? The last task!
- Is there anything that you'd like some further information on? 
- Roughly how long did it take? an hour or two
=> Not too bad this time

05-Hue-Nguyen/wk01/2-tue/index.html, 05-Hue-Nguyen/wk01/2-tue/script.js
=> submit homework w01/2-tue

15-James-Pan/wk01/2-tue/Section 1/index.html, 15-James-Pan/wk01/2-tue/Section 1/script.js, 15-James-Pan/wk01/2-tue/Section 2/index.html, 15-James-Pan/wk01/2-tue/Section 2/script.js, 15-James-Pan/wk01/2-tue/Section 3/index.html, 15-James-Pan/wk01/2-tue/Section 3/script.js, 15-James-Pan/wk01/2-tue/Section 4/index.html, 15-James-Pan/wk01/2-tue/Section 4/script.js, 15-James-Pan/wk01/2-tue/Section 5/index.html, 15-James-Pan/wk01/2-tue/Section 5/script.js
=> w1d2 homework

09-Nicole-Low/wk01/3-wed/functions.js, 09-Nicole-Low/wk01/3-wed/index.html
__________████████_____██████
_________█░░░░░░░░██_██░░░░░░█
________█░░░░░░░░░░░█░░░░░░░░░█
_______█░░░░░░░███░░░█░░░░░░░░░█
_______█░░░░███░░░███░█░░░████░█
______█░░░██░░░░░░░░███░██░░░░██
_____█░░░░░░░░░░░░░░░░░█░░░░░░░░███
____█░░░░░░░░░░░░░██████░░░░░████░░█
____█░░░░░░░░░█████░░░████░░██░░██░░█
___██░░░░░░░███░░░░░░░░░░█░░░░░░░░███
__█░░░░░░░░░░░░░░█████████░░█████████
_█░░░░░░░░░░█████_████___████_█████___█
_█░░░░░░░░░░█______█_███__█_____███_█___█
█░░░░░░░░░░░░█___████_████____██_██████
░░░░░░░░░░░░░█████████░░░████████░░░█
░░░░░░░░░░░░░░░░█░░░░░█░░░░░░░░░░░░█
░░░░░░░░░░░░░░░░░░░░██░░░░█░░░░░░██
░░░░░░░░░░░░░░░░░░██░░░░░░░███████
░░░░░░░░░░░░░░░░██░░░░░░░░░░█░░░░░█
░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░█
░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░█
░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░█ …
=> w01d03 homework submission

10-Penelope-Chen/wk01/3-wed/functions.js, 10-Penelope-Chen/wk01/3-wed/index.html
- How difficult did you find this (out of 10)? 
(0 being no problems at all, 10 being impossible) 7/10
- Was there anything that you struggled with? 
thinking about what i did wrong & getting nowhere
- Is there any particular code you want me to look into? 
just 2nd & 3rd exercises
- Is there anything that you'd like some further information on? 
hints, maybe?
- Roughly how long did it take? 
approx 1hr in total
=> so much thinky think

12-Vincent-Choi/wk01/3-wed/function.js, 12-Vincent-Choi/wk01/3-wed/index.html
=> w1d3 Homework

13-Wayne-Kenny/wk01/3-wed/index.html, 13-Wayne-Kenny/wk01/3-wed/script.js
I found the leapYear scenario to be impossible as a function. I was able to complete as a loop. Can someone please sit down with me and explain this one in detail. I am really struggling with these concepts and need help.
Functions!!
leapyear
Functions
1hr
=> Homework for Wayne

05-Hue-Nguyen/wk01/3-wed/functions.js, 05-Hue-Nguyen/wk01/3-wed/index.html
- How difficult did you find this (out of 10)? (0 being no problems at all, 10 being impossible) 
- Was there anything that you struggled with? 
- Is there anything that you'd like some further information on? 
- Roughly how long did it take? 30 min
=> submit homework wk01/3-wed

11-Tanakorn-Treechorvitaya/wk01/3-wed/function.js, 11-Tanakorn-Treechorvitaya/wk01/3-wed/index.html
- How difficult did you find this (out of 10)? (0 being no problems at all, 10 being impossible) 2
- Was there anything that you struggled with? no
- Is there any particular code you want me to look into? no
- Is there anything that you'd like some further information on? no
- Roughly how long did it take? 20 mins
=> w01d03 homework Fane

01-Andrew-Young/wk01/2-tue/hw0102index.html, 01-Andrew-Young/wk01/2-tue/hw0102script.js, 01-Andrew-Young/wk01/2-tue/js-primitives-conditionals.md, 01-Andrew-Young/wk01/3-wed/jsfunloops.js, 01-Andrew-Young/wk01/3-wed/jsfunloopsindex.html
- How difficult did you find this (out of 10)? (0 being no problems at all, 10 being impossible) 7
- Was there anything that you struggled with? Last question was challenging. 
- Is there any particular code you want me to look into? I did prompts for the last section. 
- Is there anything that you'd like some further information on? None
- Roughly how long did it take? 60-minutes
=> All homework finished

14-Wing-Fung-Lau/wk01/3-wed/functions.js, 14-Wing-Fung-Lau/wk01/3-wed/index.html
=> W1D3 homework!

02-Brianna-Danford/wk01/3-wed/functions.js, 02-Brianna-Danford/wk01/3-wed/index.html
- How difficult did you find this (out of 10)? (0 being no problems at all, 10 being impossible) 
- Was there anything that you struggled with? 
=> Functions and Loops

12-Vincent-Choi/wk01/4-thu/index.html, 12-Vincent-Choi/wk01/4-thu/script.js
=> Thurs HW needs to be finished

11-Tanakorn-Treechorvitaya/wk01/4-thu/index.html, 11-Tanakorn-Treechorvitaya/wk01/4-thu/index2.html, 11-Tanakorn-Treechorvitaya/wk01/4-thu/object.js, 11-Tanakorn-Treechorvitaya/wk01/4-thu/script.js
- How difficult did you find this (out of 10)? (0 being no problems at all, 10 being impossible) 4
- Was there anything that you struggled with? referencing
- Is there any particular code you want me to look into? line 27 script.js
- Roughly how long did it take? 2 hours
=> submit w01d04 homework Fane

08-Nick-Waddington/wk01/4-thu/index.html, 08-Nick-Waddington/wk01/4-thu/script.js
- How difficult did you find this (out of 10)? (0 being no problems at all, 10 being impossible) **7**
- Was there anything that you struggled with? - **In the 2nd exercise, getting the 'we don't have that' response to not return before getting to the menu item & adding the planet object into the system object.**
- Is there any particular code you want me to look into? - **the function I used for adding the planet object into the system object.**
- Is there anything that you'd like some further information on? - **If there's a simpler way to add objects together**
- Roughly how long did it take? **~4hrs**
=> Object and Array homework answers

04-Haoran-Guo/wk01/4-thu/coursework/index.html, 04-Haoran-Guo/wk01/4-thu/coursework/script.js, 04-Haoran-Guo/wk01/4-thu/homework/arrays_and_objects/index.html, 04-Haoran-Guo/wk01/4-thu/homework/arrays_and_objects/script.js, 04-Haoran-Guo/wk01/4-thu/warming_up/index.html
- How difficult did you find this (out of 10)? (0 being no problems at all, 10 being impossible) 3
- Roughly how long did it take? 1 hour
=> W1D4 Homework: Arrays and Objects

15-James-Pan/wk01/4-thu/index.html, 15-James-Pan/wk01/4-thu/script.js
8
The last two questions
The last two questions
The last two questions
3 hours and a half
=> w1d4 homework

09-Nicole-Low/wk01/4-thu/arrays-objects.md, 09-Nicole-Low/wk01/4-thu/index.html, 09-Nicole-Low/wk01/4-thu/objects.js, 09-Nicole-Low/wk01/4-thu/script.js
=> Nicole wk01d04 homework submission

.gitignore, 06-Jeffrey-Fazal/hwtemplate/index.html, 06-Jeffrey-Fazal/wk01/2-tue/script.js, 06-Jeffrey-Fazal/wk01/3-wed/.vscode/launch.json, 06-Jeffrey-Fazal/wk01/3-wed/functions.js, 06-Jeffrey-Fazal/wk01/3-wed/index.html, 06-Jeffrey-Fazal/wk01/3-wed/instructions.md, 06-Jeffrey-Fazal/wk01/4-thu/.vscode/launch.json, 06-Jeffrey-Fazal/wk01/4-thu/arrays-objects.md, 06-Jeffrey-Fazal/wk01/4-thu/index.html, 06-Jeffrey-Fazal/wk01/4-thu/script.js
8
Knowing which loops to use (specifically the for of loop)
For hw-4-th, line 25.
Not at the moment, but I may start asking more coding advice in class instead of struggling through the concepts
Longer than I thought it would, need to spent more time on these though.
I think the previous days homework was committed and pushed to my repo, but no PR was made.
=> Incomplete 

02-Brianna-Danford/wk01/4-thu/index.html, 02-Brianna-Danford/wk01/4-thu/script.js
=> Arrays and Objects

13-Wayne-Kenny/wk01/4-thu/index.html, 13-Wayne-Kenny/wk01/4-thu/script.js
10/10
Everything. Arrays/Functions/Loops were all mind-blowing
I think it should be ok but keen to know what I can do to make my code more efficient
Everything we did over the last 2 days
5-6 hours
=> Near Impossible to do

09-Nicole-Low/wk01/5-fri/README.md, 09-Nicole-Low/wk01/5-fri/index.html, 09-Nicole-Low/wk01/5-fri/script.js
Just a .js file full of if statements and some other useless files, nothing special...
=> Nicole wk1d5 homework submission

05-Hue-Nguyen/wk01/5-fri/index.html, 05-Hue-Nguyen/wk01/5-fri/script.js
- Roughly how long did it take? 3.5 hours
=> Submit wk01 weekend homework (MTA)

11-Tanakorn-Treechorvitaya/wk01/5-fri/index.html, 11-Tanakorn-Treechorvitaya/wk01/5-fri/script.js
- How difficult did you find this (out of 10)? (0 being no problems at all, 10 being impossible) 4
- Was there anything that you struggled with? plan the concept before start to code
- Is there any particular code you want me to look into? -
- Is there anything that you'd like some further information on? anyway to make it more efficient
- Roughly how long did it take? 1 hr
=> submit hw w01d05 Fane

15-James-Pan/wk01/5-fri/index.html, 15-James-Pan/wk01/5-fri/script.js
=> w1d5 homework

14-Wing-Fung-Lau/wk01/5-fri/index.html, 14-Wing-Fung-Lau/wk01/5-fri/plantrip.js
=> Modified some codes

04-Haoran-Guo/wk01/5-fri/homework/MTA/.idea/.gitignore, 04-Haoran-Guo/wk01/5-fri/homework/MTA/.idea/.name, 04-Haoran-Guo/wk01/5-fri/homework/MTA/.idea/MTA.iml, 04-Haoran-Guo/wk01/5-fri/homework/MTA/.idea/modules.xml, 04-Haoran-Guo/wk01/5-fri/homework/MTA/.idea/vcs.xml, 04-Haoran-Guo/wk01/5-fri/homework/MTA/README.md, 04-Haoran-Guo/wk01/5-fri/homework/MTA/index.html, 04-Haoran-Guo/wk01/5-fri/homework/MTA/script.js
=> MTA homework

01-Andrew-Young/wk01/4-thu/arrobjindex.html, 01-Andrew-Young/wk01/4-thu/arrobjscript.js
=> Homework Finished

03-Debora-Jardim/wk01/4-thu/README.md, 03-Debora-Jardim/wk01/4-thu/index.html, 03-Debora-Jardim/wk01/4-thu/object.js, 03-Debora-Jardim/wk01/4-thu/script.js
=> homework Thursday

15-James-Pan/wk01/5-fri/script.js
=> fixed some bugs

07-John-Childs-Eddy/wk01/5-fri/MTA/README.md, 07-John-Childs-Eddy/wk01/5-fri/MTA/index.html, 07-John-Childs-Eddy/wk01/5-fri/MTA/script.js
=> Completed for one line but did not successfully link the lines

02-Brianna-Danford/wk02/1-mon/index.html, 02-Brianna-Danford/wk02/1-mon/style.css
=> Holiday Season Webpage

15-James-Pan/wk02/3-wed/dom-manipulation/index.html, 15-James-Pan/wk02/3-wed/dom-manipulation/script.js, 15-James-Pan/wk02/3-wed/dom-manipulation/style.css
=> DOM Manipulation

14-Wing-Fung-Lau/wk02/4-thu/duck-hunt/duckhunt.css, 14-Wing-Fung-Lau/wk02/4-thu/duck-hunt/duckhunt.js, 14-Wing-Fung-Lau/wk02/4-thu/duck-hunt/index.html
=> Added a countdown timer!

15-James-Pan/wk02/4-thu/duck-hunt/duckhunt.css, 15-James-Pan/wk02/4-thu/duck-hunt/duckhunt.js, 15-James-Pan/wk02/4-thu/duck-hunt/index.html
=> w2d4 homework

04-Haoran-Guo/wk02/4-thu/duck-hunt/duckhunt.js
=> fix the checkForWinner function

15-James-Pan/wk02/4-thu/duck-hunt/duckhunt.js, 15-James-Pan/wk02/4-thu/duck-hunt/index.html, 15-James-Pan/wk04/1-mon/REPL.rb, 15-James-Pan/wk04/1-mon/calc.rb
=> Fixed bugs

13-Wayne-Kenny/wk01/5-fri/index.html, 13-Wayne-Kenny/wk01/5-fri/script.js, 13-Wayne-Kenny/wk04/1-mon/calc.rb
10, this was beyond impossible for me
understanding the logic of what i needed to do and how I could actually do it
15 hours
=> better late than never

08-Nick-Waddington/wk04/1-mon/BMI.rb, 08-Nick-Waddington/wk04/1-mon/calc.rb, 08-Nick-Waddington/wk04/1-mon/mortgage.rb, 08-Nick-Waddington/wk04/1-mon/trip.rb
- How difficult did you find this (out of 10)? (0 being no problems at all, 10 being impossible) - 7
- Was there anything that you struggled with? - Working out the trip equations + mortgage calculation (not working), converting trip time into hours and minutes (not completed)
- Is there any particular code you want me to look into? - The mortgage calculation, **n not recognising the n variable
- Is there anything that you'd like some further information on? How do I avoid DRY code with the calculator problem?
- Roughly how long did it take? ~3 1/2 - 4hrs
=> Week 4 Monday homework

04-Haoran-Guo/wk04/1-mon/calc.rb
=> calculator done including the bonus

05-Hue-Nguyen/wk04/1-mon/bmi_calc.rb, 05-Hue-Nguyen/wk04/1-mon/calc.rb, 05-Hue-Nguyen/wk04/1-mon/mortgage_calc.rb, 05-Hue-Nguyen/wk04/1-mon/trip_calc.rb
=> except the repl challenge

11-Tanakorn-Treechorvitaya/wk04/1-mon/BMIcalhw.rb, 11-Tanakorn-Treechorvitaya/wk04/1-mon/calculatorhw.rb, 11-Tanakorn-Treechorvitaya/wk04/1-mon/calculatorhw_main.rb, 11-Tanakorn-Treechorvitaya/wk04/1-mon/tripcalhw.rb
=> fix bmi naming problem

02-Brianna-Danford/wk02/4-thu/README.md, 02-Brianna-Danford/wk02/4-thu/duck-hunt.code-workspace, 02-Brianna-Danford/wk02/4-thu/duckhunt.css, 02-Brianna-Danford/wk02/4-thu/duckhunt.js, 02-Brianna-Danford/wk02/4-thu/index.html, 02-Brianna-Danford/wk04/1-mon/01-ruby/calculator.rb
- How difficult did you find this (out of 10)? (0 being no problems at all, 10 being impossible) 5
My whole night
=> Calculator HW

04-Haoran-Guo/wk04/2-tue/MTA/.idea/.gitignore, 04-Haoran-Guo/wk04/2-tue/MTA/.idea/MTA.iml, 04-Haoran-Guo/wk04/2-tue/MTA/.idea/modules.xml, 04-Haoran-Guo/wk04/2-tue/MTA/.idea/vcs.xml, 04-Haoran-Guo/wk04/2-tue/MTA/MTA.rb, 04-Haoran-Guo/wk04/2-tue/MTA/README.md
=> MTA done in Ruby

05-Hue-Nguyen/wk04/2-tue/mta.rb
=> mta in Ruby

14-Wing-Fung-Lau/wk04/2-tue/mta.rb
=> Ah shit, here we go again.

11-Tanakorn-Treechorvitaya/wk04/2-tue/MTA.rb
- How difficult did you find this (out of 10)? (0 being no problems at all, 10 being impossible) 4
- Was there anything that you struggled with? concept for start and end
- Roughly how long did it take? 2
=> Finished hw w04d02 Fane

09-Nicole-Low/wk04/2-tue/trip_planner.rb
=> Nicole wk4d2 homework submission

08-Nick-Waddington/wk04/2-tue/MTA.rb
- How difficult did you find this (out of 10)? (0 being no problems at all, 10 being impossible) 8
- Was there anything that you struggled with? -  Getting the values and number of stops to print out correctly, working out how to get multiple train lines to work, how to stop bugs if the user chooses Union Square, repeating myself
- Is there any particular code you want me to look into? 
- Is there anything that you'd like some further information on? - Interested to see everybody else's code
- Roughly how long did it take? ~7-8hrs (then I got distracted trying to get colours and ascii art to work)
=> Week 4 Tuesday Homework - MTA

13-Wayne-Kenny/wk04/2-tue/MTA.rb
This was a 9 out of 10 until I realised how to do the first line from start to finish thanks to others. After that it became a 6 out of 10
problem solving and working through the logic at the start
can you look into my menu options at the start. if user input is incorrect I want the program to exit
3 hours
=> Did it with inspiration from others

02-Brianna-Danford/wk04/2-tue/mta.rb
=> MTA Lab Ruby

13-Wayne-Kenny/wk04/3-wed/book_finder/main.rb, 13-Wayne-Kenny/wk04/3-wed/book_finder/public /css/book.css, 13-Wayne-Kenny/wk04/3-wed/book_finder/views/home.erb, 13-Wayne-Kenny/wk04/3-wed/book_finder/views/info.erb, 13-Wayne-Kenny/wk04/3-wed/book_finder/views/layout.erb
This one was pretty difficult 7 out of 10
I struggled with the correct syntax for linking to the url
I can't seem to get my css to update anything on my page. I haven't been able to do this for any of the work we did today. can you please review my code and let me know where I am going wrong
just the css stuff mentioned above
2 hours
=> completed the bare minimum

14-Wing-Fung-Lau/wk04/3-wed/main.rb, 14-Wing-Fung-Lau/wk04/3-wed/public/css/books.css, 14-Wing-Fung-Lau/wk04/3-wed/views/home.erb, 14-Wing-Fung-Lau/wk04/3-wed/views/info.erb, 14-Wing-Fung-Lau/wk04/3-wed/views/layout.erb
=> Ban this Google Books API

10-Penelope-Chen/wk04/3-wed/books-one/main.rb, 10-Penelope-Chen/wk04/3-wed/books-one/public/css/books-one.css, 10-Penelope-Chen/wk04/3-wed/books-one/views/home.erb, 10-Penelope-Chen/wk04/3-wed/books-one/views/info.erb, 10-Penelope-Chen/wk04/3-wed/books-one/views/layout.erb
6
making the CSS appear & ruby work
N/A
N/A
90min~
=> Books 1 in Ruby/Erb/CSS

04-Haoran-Guo/wk04/3-wed/.idea/.gitignore, 04-Haoran-Guo/wk04/3-wed/.idea/3-wed.iml, 04-Haoran-Guo/wk04/3-wed/.idea/misc.xml, 04-Haoran-Guo/wk04/3-wed/.idea/modules.xml, 04-Haoran-Guo/wk04/3-wed/.idea/vcs.xml, 04-Haoran-Guo/wk04/3-wed/books_i/main.rb, 04-Haoran-Guo/wk04/3-wed/books_i/public/style/style.css, 04-Haoran-Guo/wk04/3-wed/books_i/views/home.erb, 04-Haoran-Guo/wk04/3-wed/books_i/views/layout.erb, 04-Haoran-Guo/wk04/3-wed/books_i/views/result.erb
=> fun book search

09-Nicole-Low/wk04/3-wed/book_search/public/css/book_search.css, 09-Nicole-Low/wk04/3-wed/book_search/views/layout.erb
Figured out how to make the background transparent from the one and only Sophie
=> Nicole wk4d3 updated homework submission

09-Nicole-Low/wk05/2-tue/marine-life/app/views/animals/add.html.erb, 09-Nicole-Low/wk05/2-tue/marine-life/app/views/animals/edit.html.erb, 09-Nicole-Low/wk05/2-tue/marine-life/app/views/animals/index.html.erb, 09-Nicole-Low/wk05/2-tue/marine-life/app/views/animals/info.html.erb
I now know how to but a button tag in a link 👯
=> Nicole wk5d2 homework update

10-Penelope-Chen/wk07/1-mon/gg_books/index.html, 10-Penelope-Chen/wk07/1-mon/gg_books/js/gg_books.js
=> AJAX (more like AJAJ for hw)

08-Nick-Waddington/wk07/1-mon/books/index.html, 08-Nick-Waddington/wk07/1-mon/books/js/books.js
- Roughly how long did it take? ~1-2hrs
I'm too tired tonight, will come back and finish this another time.
=> Week 7 Monday homework - not really finished

14-Wing-Fung-Lau/wk04/5-fri/main.rb, 14-Wing-Fung-Lau/wk04/5-fri/views/countries_show.erb, 14-Wing-Fung-Lau/wk07/1-mon/index.html, 14-Wing-Fung-Lau/wk07/1-mon/js/book.js
=> Literary inquisition

12-Vincent-Choi/wk07/1-mon/index.html, 12-Vincent-Choi/wk07/1-mon/js/books.js
=> Book Search things~

02-Brianna-Danford/wk05/3-wed/library/app/views/authors/index.html.erb, 02-Brianna-Danford/wk07/1-mon/index.html, 02-Brianna-Danford/wk07/1-mon/js/books.js
=> single page app google book search using ajax

08-Nick-Waddington/wk07/2-tue/jQuery-practise/css/style.css, 08-Nick-Waddington/wk07/2-tue/jQuery-practise/index.html, 08-Nick-Waddington/wk07/2-tue/jQuery-practise/js/jquery.js, 08-Nick-Waddington/wk07/2-tue/jQuery-practise/js/script.js
- How difficult did you find this (out of 10)? (0 being no problems at all, 10 being impossible) 6
- Is there anything that you'd like some further information on? why do random duck + random fox not have CORS enabled ):
- Roughly how long did it take? ~4hrs
=> Week 7 Tuesday Homework

13-Wayne-Kenny/wk07/2-tue/jQuery_HW/index.html, 13-Wayne-Kenny/wk07/2-tue/jQuery_HW/js/fact.js, 13-Wayne-Kenny/wk07/2-tue/jQuery_HW/js/jquery.js
6/10
finding an api that worked
2 hours
=> ignore HW2 - moved on to Big O instead

14-Wing-Fung-Lau/wk07/2-tue/wiki-search/index.html, 14-Wing-Fung-Lau/wk07/2-tue/wiki-search/js/jquery.js, 14-Wing-Fung-Lau/wk07/2-tue/wiki-search/js/wiki.js
=> Why is Wikipedia banned in some countries?

06-Jeffrey-Fazal/wk07/1-mon/.gitkeep, 06-Jeffrey-Fazal/wk07/1-mon/.vscode/settings.json, 06-Jeffrey-Fazal/wk07/1-mon/brief.md, 06-Jeffrey-Fazal/wk07/1-mon/index.html, 06-Jeffrey-Fazal/wk07/1-mon/js/main.js, 06-Jeffrey-Fazal/wk07/1-mon/js/response.json, 06-Jeffrey-Fazal/wk07/2-tue/brief.md, 06-Jeffrey-Fazal/wk07/2-tue/index.html, 06-Jeffrey-Fazal/wk07/2-tue/js/api.js, 06-Jeffrey-Fazal/wk07/2-tue/js/jquery.js
- part 1 completed
-  updating files
- updated dom story
- Submitting previous work
- ruby calc v1
- Ruby calculator simple
- Framework for bonus section
- MTA semi working on one line
- working copy of wed hw
- all
- test
- eight ball plus prework
- carnvial games push
- wk05-2 inital setup
- Issues with MVC
- pre books migration
- testing associations and seed csv
- adding files
- im progress
- console log showing things
- basics done
=> basic hw submission

09-Nicole-Low/wk07/2-tue/bigO/big-o.md, 09-Nicole-Low/wk07/2-tue/bigO/bigOExercises.txt, 09-Nicole-Low/wk07/2-tue/countries/index.html, 09-Nicole-Low/wk07/2-tue/countries/js/jquery.js, 09-Nicole-Low/wk07/2-tue/countries/js/script.js, 09-Nicole-Low/wk07/2-tue/disney/index.html, 09-Nicole-Low/wk07/2-tue/disney/js/jquery.js, 09-Nicole-Low/wk07/2-tue/disney/js/script.js, 09-Nicole-Low/wk07/2-tue/fishes/index.html, 09-Nicole-Low/wk07/2-tue/fishes/js/jquery.js, 09-Nicole-Low/wk07/2-tue/fishes/js/script.js
=> Nicole wk7d2 homework submission

10-Penelope-Chen/wk07/2-tue/hw-jquery/index.html, 10-Penelope-Chen/wk07/2-tue/hw-jquery/js/hw.js
=> finished hw: jquery.ajax for hobbies

08-Nick-Waddington/wk07/3-wed/flickr/css/style.css, 08-Nick-Waddington/wk07/3-wed/flickr/index.html, 08-Nick-Waddington/wk07/3-wed/flickr/js/jquery.js, 08-Nick-Waddington/wk07/3-wed/flickr/js/search.js, 08-Nick-Waddington/wk07/3-wed/flickr/js/underscore.js
- How difficult did you find this (out of 10)? (0 being no problems at all, 10 being impossible) 8
- Was there anything that you struggled with? Working out where to put the current_page variable + where to have it increment, thinking of a way to stop multiple requests when scrolling
- Roughly how long did it take? ~3-4hrs
=> Week 7 Wednesday homework

08-Nick-Waddington/wk07/4-thu/recursion-exercises/.gitignore, 08-Nick-Waddington/wk07/4-thu/recursion-exercises/floodIt-challenge/README.md, 08-Nick-Waddington/wk07/4-thu/recursion-exercises/floodIt-challenge/app.js, 08-Nick-Waddington/wk07/4-thu/recursion-exercises/floodIt-challenge/index.html, 08-Nick-Waddington/wk07/4-thu/recursion-exercises/floodIt-challenge/style.css, 08-Nick-Waddington/wk07/4-thu/recursion-exercises/package-lock.json, 08-Nick-Waddington/wk07/4-thu/recursion-exercises/package.json, 08-Nick-Waddington/wk07/4-thu/recursion-exercises/readme.md, 08-Nick-Waddington/wk07/4-thu/recursion-exercises/recursion.js, 08-Nick-Waddington/wk07/4-thu/recursion-exercises/test/index.js
- How difficult did you find this (out of 10)? (0 being no problems at all, 10 being impossible) Q1 - Q3 = 7-8, Q4 + Q5 = 10
- Was there anything that you struggled with? - Knowing when, how and what to return, 'InternalError: too much recursion', thinking of a base case that makes sense and works.
- Is there any particular code you want me to look into? The arrayRange function for the factorial question, I kind of get what it's doing, but I don't really understand what's going on in the Array.from(). 
- Is there anything that you'd like some further information on? How to make my first answer not diabolical (how to deal with the negative numbers test + any given negative number)
- Roughly how long did it take? ~5-6hrs
=> Week 7 Thursday homework

14-Wing-Fung-Lau/wk07/3-wed/image-search/js/search.js, 14-Wing-Fung-Lau/wk07/4-thu/recursion-exercises/.gitignore, 14-Wing-Fung-Lau/wk07/4-thu/recursion-exercises/floodIt-challenge/README.md, 14-Wing-Fung-Lau/wk07/4-thu/recursion-exercises/floodIt-challenge/app.js, 14-Wing-Fung-Lau/wk07/4-thu/recursion-exercises/floodIt-challenge/index.html, 14-Wing-Fung-Lau/wk07/4-thu/recursion-exercises/floodIt-challenge/style.css, 14-Wing-Fung-Lau/wk07/4-thu/recursion-exercises/package-lock.json, 14-Wing-Fung-Lau/wk07/4-thu/recursion-exercises/package.json, 14-Wing-Fung-Lau/wk07/4-thu/recursion-exercises/readme.md, 14-Wing-Fung-Lau/wk07/4-thu/recursion-exercises/recursion.js, 14-Wing-Fung-Lau/wk07/4-thu/recursion-exercises/test/index.js
=> Recursion is difficult!

05-Hue-Nguyen/wk07/2-tue/shakespeare/index.html, 05-Hue-Nguyen/wk07/2-tue/shakespeare/js/jquery.js, 05-Hue-Nguyen/wk07/2-tue/shakespeare/js/script.js, 05-Hue-Nguyen/wk07/2-tue/shakespeare/styles.css
=> homework 2-tue

09-Nicole-Low/wk10/4-thu/search-algorithms/searches.js
=> binary recursive search

09-Nicole-Low/wk10/5-fri/linked-lists/.gitignore, 09-Nicole-Low/wk10/5-fri/linked-lists/LinkedList.js, 09-Nicole-Low/wk10/5-fri/linked-lists/package-lock.json, 09-Nicole-Low/wk10/5-fri/linked-lists/package.json, 09-Nicole-Low/wk10/5-fri/linked-lists/readme.md, 09-Nicole-Low/wk10/5-fri/linked-lists/test/index.js
=> wk10d5 homework submission
